config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :prestations, except: :destroy do
    member do
      patch :finish
    end
  end

  # POST "prestations/51/finish"
  # post "prestations/finish", to: 'prestations#finish', as: :finish_prestation

  resources :tasks, only: [:index, :show, :edit, :update] do
    collection do
      get :calendar
    end

    member do
      get :index
      patch :mark_as_urgent
      patch :mark_as_done
    end
  end

  resources :clients, only: [:index, :show]
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  CATEGORIES = ['Mariage', 'Famille', 'Entreprise']
  STATUS = ['progress', 'finish']

  attr_accessor :new_client

  belongs_to :client
  has_many :tasks
  has_one_attached :photo

  accepts_nested_attributes_for :client, reject_if: proc { |attributes| attributes[:first_name].blank? }


  validates :title, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :location, presence: true
  validates :status, presence: true, inclusion: { in: STATUS }
end

app/controllers/prestations_controller.rb
class PrestationsController < ApplicationController
  before_action :set_prestation, only: %i[show edit update finish]

  def index
    @prestations = Prestation.joins(:client).where(clients: { user_id: current_user.id }).order(status: :desc).order(:start_date)
  end

  def show; end

  def new
    @prestation = Prestation.new
    @display_client_names = Client.order(:last_name).map do |client|
      client_company = client.company_name.nil? ? "" : " (Entreprise: '#{client.company_name}')"
      client_name = client.first_name + " " + client.last_name += client_company
      [client_name, client.id]
    end
    @prestation.build_client
  end

  def create
    @prestation = Prestation.new(prestation_params)

    if @prestation.category == 'Entreprise'
      @prestation.title = "#{@prestation.category} #{@prestation.client.company_name}"
    else
      @prestation.title = "#{@prestation.category} #{@prestation.client.last_name}"
    end

    @prestation.client.user = current_user

    if @prestation.save

      if @prestation.category == 'Mariage'
        create_mariage_tasks(@prestation, @prestation.start_date, @prestation.end_date)
      elsif @prestation.category == 'Entreprise'
        create_entreprise_tasks(@prestation, @prestation.start_date, @prestation.end_date)
      elsif @prestation.category == 'Famille'
        create_famille_tasks(@prestation, @prestation.start_date, @prestation.end_date)
      end

      redirect_to prestation_path(@prestation)
    else
      render :new
    end
  end

  def finish
    @prestation.update(status: "finish")
    redirect_to prestation_path
  end

  def edit; end

  def update
    @prestation.update(prestation_params)
    # @prestation.tasks.destroy_all

    # if @prestation.category == 'Mariage'
    #   create_mariage_tasks(@prestation, @prestation.start_date, @prestation.end_date)
    # elsif @prestation.category == 'Entreprise'
    #   create_entreprise_tasks(@prestation, @prestation.start_date, @prestation.end_date)
    # elsif @prestation.category == 'Famille'
    #   create_famille_tasks(@prestation, @prestation.start_date, @prestation.end_date)
    # end

    if @prestation.save
    redirect_to prestation_path(@prestation)

    else
      render :edit
    end
  end

  private

  def set_prestation
    @prestation = current_user.prestations.find(params[:id])
  end

  def prestation_params
    params.require(:prestation).permit(:category, :location, :notes, :start_date, :end_date, :client_id, client_attributes: [:id, :first_name, :last_name, :address, :phone_number, :email, :tutoiement, :partner_name, :notes, :photo])
  end

  def create_famille_tasks(prestation, event_start_date, event_end_date)
    task1_famille = Task.create!(
                        prestation: prestation,
                        name: "Envoyer contrat & facture",
                        kind: 'admin',
                        urgent: false,
                        start_date: Date.today,
                        end_date: Date.today)
    task2_famille = Task.create!(
                        prestation: prestation,
                        name: "Valider réception contrat signé",
                        kind: 'admin',
                        description: "Si le document n'a pas été reçu : relancer le client",
                        urgent: false,
                        start_date: Date.today + 7.days,
                        end_date: Date.today + 7.days)
    task3_famille = Task.create!(
                        prestation: prestation,
                        name: "Confirmer date & lieu",
                        kind: 'admin',
                        description: "Contacter la famille",
                        urgent: false,
                        start_date: event_start_date - 7.days,
                        end_date: event_start_date - 7.days)
    task4_famille = Task.create!(
                        prestation: prestation,
                        name: "Évènement",
                        kind: 'évènement',
                        urgent: false,
                        start_date: event_start_date,
                        end_date: event_end_date)
    task5_famille = Task.create!(
                        prestation: prestation,
                        name: "Recevoir solde total",
                        kind: 'admin',
                        description: "A recevoir au moment de la prestation",
                        urgent: false,
                        start_date: event_end_date,
                        end_date: event_end_date)
    task6_famille = Task.create!(
                        prestation: prestation,
                        name: "Post-traitement",
                        kind: 'créa',
                        description: "Marge de 30 jours max pour traiter les photos",
                        urgent: false,
                        start_date: event_end_date + 1.day,
                        end_date: event_end_date + 1.day)
    task7_famille = Task.create!(
                        prestation: prestation,
                        name: "Envoyer galerie photos",
                        kind: 'admin',
                        description: "Envoyer la galerie en ligne par mail (avec les codes d’accès et le fonctionnement de leur accès privé) ",
                        urgent: false,
                        start_date: event_end_date + 30.days,
                        end_date: event_end_date + 30.days)
    task8_famille = Task.create!(
                        prestation: prestation,
                        name: "Envoyer support(s) photo",
                        kind: 'admin',
                        description: "Par courrier",
                        urgent: false,
                        start_date: event_end_date + 40.days,
                        end_date: event_end_date + 40.days)
  end

  def create_entreprise_tasks(prestation, event_start_date, event_end_date)
    task1_entreprise = Task.create!(
                        prestation: prestation,
                        name: 'Envoyer contrat',
                        kind: 'admin',
                        urgent: false,
                        start_date: Date.today,
                        end_date: Date.today)

    task2_entreprise = Task.create!(
                        prestation: prestation,
                        name: 'Valider réception contrat signé',
                        kind: 'admin',
                        description: "Si le document n'a pas été reçu : relancer le client",
                        urgent: false,
                        start_date: Date.today + 3.days,
                        end_date: Date.today + 3.days)

    task3_entreprise = Task.create!(
                        prestation: prestation,
                        name: 'Brief',
                        kind: 'rendez-vous',
                        description: "Discussion avec le client sur le brief de la prestation",
                        urgent: false,
                        start_date: event_start_date - 7.days,
                        end_date: event_start_date - 7.days)

    task4_entreprise = Task.create!(
                        prestation: prestation,
                        name: 'Évènement',
                        kind: 'évènement',
                        urgent: false,
                        start_date: event_start_date,
                        end_date: event_end_date)

    task5_entreprise = Task.create!(
                        prestation: prestation,
                        name: 'Post-traitement',
                        kind: 'créa',
                        description: "Marge de 7 jours pour traiter les photos",
                        urgent: false,
                        start_date: event_end_date + 1.day,
                        end_date: event_end_date + 1.day)

    task6_entreprise = Task.create!(
                        prestation: prestation,
                        name: 'Livrer photos + envoyer facture',
                        kind: 'admin',
                        urgent: false,
                        start_date: event_end_date + 7.days,
                        end_date: event_end_date + 7.days)

    task7_entreprise = Task.create!(
                        prestation: prestation,
                        name: 'Relancer paiement',
                        kind: 'admin',
                        urgent: false,
                        start_date: event_end_date + 30.days,
                        end_date: event_end_date + 30.days)

    task8_entreprise = Task.create!(
                        prestation: prestation,
                        name: 'Valider réception solde',
                        kind: 'admin',
                        description: "Si le solde n'a pas été reçu : relancer le client",
                        urgent: false,
                        start_date: event_end_date + 45.days,
                        end_date: event_end_date + 45.days)
  end

  def create_mariage_tasks(prestation, event_start_date, event_end_date)
    task1_mariage = Task.create!(
                        prestation: prestation,
                        name: "Envoyer contrat & facture 1er acompte",
                        kind: "admin",
                        urgent: false,
                        start_date: Date.today,
                        end_date: Date.today)

    task2_mariage = Task.create!(
                        prestation: prestation,
                        name: "Valider réception contrat & 1er acompte",
                        kind: "admin", description: "Si les documents et l'acompte n'ont pas été reçus : relancer le client",
                        urgent: false,
                        start_date: Date.today + 7.days,
                        end_date: Date.today + 7.days)

    task3_mariage = Task.create!(
                        prestation: prestation,
                        name: "Fixer le 1er rendez-vous",
                        kind: "admin",

app/views/prestations/_form.html.erb
<%= simple_form_for @prestation do |f| %>
          <% if @prestation.errors.any? %>
            <div class="errors-container">
              <ul>
                <% @prestation.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="start-date col">
              <%= f.input :start_date,
                          as: :string,
                          required: false,
                          input_html: {id: "datepicker"},
                          label: 'Dates' %>
            </div>
            <div class="col d-none">
              <%= f.input :end_date,
                          as: :string,
                          required: false,
                          input_html: {class: "end_date"},
                          label: 'Date de fin' %>
            </div>
          </div>
          <div class='dates-div d-none'>
            <label>Dates</label>
              <input type="text" id="range-dates">
          </div>
            <%= f.input :category,
                        as: :select,
                        collection: Prestation::CATEGORIES,
                        input_html: {class: "select2"},
                        label: 'Catégorie',
                        placeholder: 'Sélectionner le type de la prestation' %>


            <%= f.input :location,
                        as: :string,
                        input_html: {id: "autocomplete-location-1"},
                        label: 'Lieu',
                        placeholder: "Indiquer l'adresse de la prestation" %>

            <%= f.input :notes,
                        as: :text,
                        label: 'Notes',
                        placeholder: "Ajouter des informations sur la prestation" %>

            <%= f.input :new_client,
                        label: "nouveau client ?",
                        as: :boolean %>

            <div class="existing-client">
              <%= f.association :client,
                          required: false,
                          input_html: {class: "select2"},
                          label: 'Client',
                          collection: @display_client_names %>
              <div class="d-flex flex-row-reverse mt-4">
                <%= f.submit "Créer", class: 'pho-btn' %>
              </div>
            </div>

          <div class="new-client d-none">
            <h2>Nouveau client</h2>
            <div class="row">
            <div class="col">
            <%= f.simple_fields_for :client do |c| %>
                      <%= c.input :first_name, as: :string, label: 'Prénom', placeholder: "Prénom" %>
                      <%= c.input :last_name, as: :string, label: 'Nom', placeholder: 'Nom' %>
                      <%= c.input :address, as: :string, input_html: {id: "autocomplete-location-2"}, label: "Indiquer l'adresse du client", placeholder: 'Adresse' %>
                      <%= c.input :phone_number, as: :string, label: 'Téléphone', placeholder: '0625252525' %>
                      <%= c.input :email, as: :string, label: 'Email', placeholder: 'photographe@example.com' %>
                      <%= c.input :partner_name, as: :string, label: 'Nom du partenaire', placeholder: 'Indiquer le prénom et nom du partenaire' %>
                      <%= c.input :tutoiement, as: :boolean %>
                      <%= c.input :notes, as: :text, label: 'Notes', placeholder: 'Ajouter des informations sur le client' %>
                      <%= c.input :photo, as: :file %>
                      <% end %>
            </div>
          </div>
            <div class="d-flex flex-row-reverse mt-4">
              <%= f.submit "Créer", class: 'pho-btn' %>
            </div>
        <% end %>

app/views/prestations/edit.html.erb
<div class="container prestation-form">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="form-post mb-5">
        <h1 class="mt-3 mb-5">Modifier la prestation<span class="green-point">.</span></h1>
        <%= simple_form_for @prestation do |f| %>
          <% if @prestation.errors.any? %>
            <div class="errors-container">
              <ul>
                <% @prestation.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="start-date col">
              <%= f.input :start_date,
                          as: :string,
                          required: false,
                          input_html: {class: "datepicker"},
                          label: 'Date de début' %>
            </div>
            <div class="end-date col">
              <%= f.input :end_date,
                          as: :string,
                          required: false,
                          input_html: {id: "end_date", class: "end_date"},
                          label: 'Date de fin' %>
            </div>
          </div>
          <div class='dates-div d-none'>
            <label>Dates</label>
              <input type="text" id="range-dates">
          </div>

            <%= f.input :location,
                        as: :string,
                        input_html: {id: "autocomplete-location-1"},
                        label: 'Lieu',
                        placeholder: "Indiquer l'adresse de la prestation" %>

            <%= f.input :notes,
                        as: :text,
                        label: 'Notes',
                        placeholder: "Ajouter des informations sur la prestation" %>


          <div class="new-client">
            <h2>Modifier le client</h2>
            <div class="row">
            <div class="col">
            <%= f.simple_fields_for :client do |c| %>
                      <%= c.input :first_name, as: :string, label: 'Prénom', placeholder: "Prénom" %>
                      <%= c.input :last_name, as: :string, label: 'Nom', placeholder: 'Nom' %>
                      <%= c.input :address, as: :string, input_html: {id: "autocomplete-location-2"}, label: "Indiquer l'adresse du client", placeholder: 'Adresse' %>
                      <%= c.input :phone_number, as: :string, label: 'Téléphone', placeholder: '0625252525' %>
                      <%= c.input :email, as: :string, label: 'Email', placeholder: 'photographe@example.com' %>
                      <%= c.input :partner_name, as: :string, label: 'Nom du partenaire', placeholder: 'Indiquer le prénom et nom du partenaire' %>
                      <%= c.input :tutoiement, as: :boolean %>
                      <%= c.input :notes, as: :text, label: 'Notes', placeholder: 'Ajouter des informations sur le client' %>
                      <%= c.input :photo, as: :file %>
                      <% end %>
            </div>
          </div>
            <div class="d-flex flex-row-reverse mt-4">
              <%= f.submit "Modifier", class: 'pho-btn' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/prestations/show.html.erb
<div class="d-flex w-100" id="show-prestation">
  <div class="show-presta-client">

      <h1 class="mt-5 ml-5"> <%= @prestation.category %><span class="green-point">.</span></h1>

    <div class="show-prestation-place-date d-flex align-items-center justify-content-between">
      <div class="div1">
        <% if @prestation.start_date != @prestation.end_date %>
            <p class="event-date-show-prestation show-presta-color font-weight-bold ml-5 mb-2"><i class="far fa-calendar-alt icon mr-2"></i><%= l(@prestation.start_date, format: '%d') %> - <%= l(@prestation.end_date, format: '%d %B %Y') %></p>
        <% else %>
            <p class="event-date-show-prestation show-presta-color font-weight-bold ml-5 mb-2"><i class="far fa-calendar-alt icon mr-2"></i><%= l(@prestation.start_date, format: '%d %B %Y') %></p>
        <% end %>
        <p><i class="fas fa-map-marker-alt ml-5 mb-5 icon-gray mr-2"></i><%= @prestation.location %></p>
      </div>
      <div class="div2">
        <%= link_to 'Modifier', edit_prestation_path(@prestation), class: "pho-btn px-2 mr-5" %>
      </div>
    </div>
    <div class="px-5">
      <p class="border-bottom-light-gray mb-5"></p>
    </div>

    <div>
      <li><%= link_to(client_path(id: @prestation.client.id), class: "link-to-client") do %>
        <h2 class="mx-5 mb-4"><%= @prestation.client.first_name %> <%= @prestation.client.last_name %></h2>
      <% end %>
      <div class="d-flex ml-5 align-items-center">
        <div>
          <%= cl_image_tag @prestation.client.photo.key, crop: :fill, width: 250, height: 250, class: "photo-client" %>
        </div>
        <div class="ml-5">
          <p class="pb-3 p-gray"><i class="fas fa-envelope icon-gray mr-2"></i><%= @prestation.client.email %></p>
          <p class="pb-3 p-gray"> <i class="fas fa-phone icon-gray mr-2"></i><%= @prestation.client.phone_number %> </p>
          <p class="pb-3 p-gray"> <i class="fas fa-home icon-gray mr-2"></i><%= @prestation.client.address  %> </p>
          <% if @prestation.client.partner_name.nil? == false %>
            <p class="pb-3 p-gray"> <i class="fas fa-plus-circle icon-gray mr-2"></i>  <%= @prestation.client.partner_name %> </p>
          <% end %>
          <%if @prestation.client.tutoiement == true %>
            <p class="pb-3 p-gray"><i class="fas fa-comment icon-gray mr-2"></i>  On se tutoie </i></p>
          <% else %>
            <p class="pb-3 p-gray"><i class="fas fa-comment icon-gray mr-2"></i>  On se vouvoie </i></p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="px-5">
      <p class="border-bottom-light-gray mt-5"></p>
    </div>

    <div class="mx-5 mb-5 mt-5">
      <h2>Notes</h2>
         <p class="mt-2 pb-5"><%= @prestation.notes %></p>
    </div>

  </div>


  <div class="show-presta-taches">
    <h2>Tâches</h2>
    <div class="show-presta-border-taches pr-5 w-100">
      <p class="border-bottom-medium-gray"></p>
    </div>


      <div>
        <ul class="container-fluid mt-5">
          <% @prestation.tasks.each do |task| %>
            <li class="card-task white-hover row align-items-center justify-content-between py-2 px-4 mr-4">
              <!-- URGENT TAG-->
              <%= link_to mark_as_urgent_task_path(task), class: "link-mark-as-urgent", method: :patch, remote: true do %>
                <% if task.kind == 'admin' || task.kind == 'rendez-vous' %>
                  <% if task.urgent == true %>
                    <div id="tag-urgent-<%= task.id %>" class="urgent px-0"><i class="fas fa-thumbtack"></i></div>
                  <% else %>
                    <div id="tag-urgent-<%= task.id %>" class="p-gray px-0"><i class="fas fa-thumbtack"></i></div>
                  <% end %>
                <% elsif task.kind == 'évènement' %>
                  <% if task.end_date < Date.today  %>
                    <div id="tag-urgent-<%= task.id %>" class="px-0"><i class="p-gray fas fa-camera"></i></div>
                  <% else %>
                    <div id="tag-urgent-<%= task.id %>" class="px-0"><i class="p-gray fas fa-camera"></i></div>
                  <% end %>
                <% else %>
                  <% if task.urgent == true %>
                    <div id="tag-urgent-<%= task.id %>" class="urgent px-0"><i class="fas fa-palette"></i></div>
                  <% else %>
                    <div id="tag-urgent-<%= task.id %>" class="p-gray px-0"><i class="fas fa-palette"></i></div>
                  <% end %>
                <% end %>
              <% end %>

              <!-- DONE TAG -->
              <%= link_to mark_as_done_task_path(task), class: "link-mark-as-done", method: :patch, remote: true do %>
                <% if task.done %>
                  <div id="tag-done-<%= task.id %>" class="tag-done green pl-2 pr-0"><i class="fas fa-check"></i></div>
                <% else %>
                  <div id="tag-done-<%= task.id %>" class="tag-done p-gray pl-2 pr-0"><i class="fas fa-check"></i></div>
                <% end %>
              <% end %>

              <% if task.end_date < Date.today %>
                <p class="text-truncate col-8 pl-3 p-gray"><%= task.name %></p>
                <div class="col-1">
                  <div class="e-mail">
                  <%= render "tasks/emails/#{mailto_partial_for_task(task)}", task: task %>
                  </div>
                </div>
                <p class="task-prestation-client text-right p-gray pr-2 col-2"><%= l(task.start_date, format: '%d %b') %></p>
              <% elsif task.kind =='évènement' %>
                <p class="text-truncate col-8 pl-3 green font-weight-bold"><%= task.name %></p>
                <div class="col-1">
                  <div class="e-mail">
                  <%= render "tasks/emails/#{mailto_partial_for_task(task)}", task: task %>
                  </div>
                </div>
                <p class="task-prestation-client text-right col-2 p-gray pr-2 green font-weight-bold"><%= l(task.start_date, format: '%d %b') %></p>
              <% else %>
                <p class="text-truncate col-8 pl-3"><%= task.name %></p>
                <div class="col-1">
                  <div class="e-mail">
                  <%= render "tasks/emails/#{mailto_partial_for_task(task)}", task: task %>
                  </div>
                </div>
                <p class="task-prestation-client text-right col-2 p-gray pr-2"><%= l(task.start_date, format: '%d %b') %></p>
              <% end %>
              <% if task.description %>
                <div class="task-description-show d-none">
                  <p><%= task.description %></p>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>

  </div>
</div>

app/views/prestations/show_johanne.html.erb
<div class="principale-show-prestation w-100">

  <!-- Titre et boutons -->
  <div class="title-button d-flex bd-highlight">
    <div class="title-button-show-prestation col-md-8 flex-grow-1 bd-highlight">
      <h1 class="mt-5 ml-5 mb-4"> <%= @prestation.title %><span class="green-point">.</span></h1>
    </div>
    <div class="button-modifier-show-prestation col-md-2 d-flex flex-grow-1 bd-highlight">
     <p class="button-modifier">Modifier</p>
    </div>
    <div class="prestation-status-show-prestation col-md-2 d-flex flex-grow-1 bd-highlight">
      <% if @prestation.status == "progress" %>
        <%= link_to finish_prestation_path(@prestation), method: :patch, class: "presta-status"  do %>
         <p class="pho-btn d-flex px-2">Passer en terminé</p>
         <% end %>
        <% else %>
          <p class="d-flex align-tiems-center px-2 ">Terminé</p><i class="far fa-calendar-check"></i>
        <% end %>
    </div>
  </div>

  <!-- Card Taches -->
  <div class="contenu-show-prestation row d-flex pl-5 pt-2 w-100 mb-3">
    <div class="task-show-prestation col-md-5 bg-white">
      <h2 class="task-title-show-prestation pl-3 pt-4 mt-2 ml-4 mb-2 pb-2"> Tâches </h2>
      <% @prestation.tasks.each do |task| %>
        <div class="task-details-show-prestation row d-flex pl-4 ml-4 pb-4">
          <% if task.end_date < Date.today %>
             <p class="task-date-show-prestation past-date text-muted col-md-3 text-left"> <%= l(task.start_date, format: '%d %b') %></p>
             <p class="task-name-show-prestation past-date col-md-9 text-left"> <%= task.name %></p>
          <% elsif task.kind =='évènement' %>
            <p class="task-date-show-prestation date-event-task-show col-md-3 text-left"> <%= l(task.start_date, format: '%d %b') %></p>
            <p class="task-name-show-prestation date-event-task-show col-md-9 text-left"> <i class="fas fa-camera"></i> <%= task.name %></p>
          <% else %>
            <p class="task-date-show-prestation col-md-3 text-left"> <%= l(task.start_date, format: '%d %b') %></p>
            <p class="task-name-show-prestation col-md-9 text-left"> <%= task.name %></p>
          <% end %>

        </div>
      <% end %>
    </div>

    <!-- Cards evenement, client et notes -->
    <div class="evenement-client-notes-show-prestation col-md-7 d-flex flex-column justify-content-between">
      <div class="evenement-show-prestation bg-white d-flex mb-3">
        <div class="event-title-date-show-prestation col-md-6">
          <h2 class="event-title-show-prestation pl-3 pt-4 mt-2 ml-4 mb-2"> Évènement </h2>
          <% if @prestation.start_date != @prestation.end_date %>
            <p class="event-date-show-prestation pl-3 ml-4 pb-4"> <%= l(@prestation.start_date, format: '%d') %> - <%= l(@prestation.end_date, format: '%d %B') %> </p>
          <% else %>
            <p class="event-date-show-prestation pl-3 ml-4 pb-4"> <%= l(@prestation.start_date, format: '%d %B') %> </p>
          <% end %>
        </div>
        <div class="event-location-show-prestation col-md-6 d-flex">
          <p class="text-envent-location-show-prestation"><%= @prestation.location %></p>
        </div>
      </div>

      <div class="client-show-prestation bg-white d-flex mb-3">
        <div class="info-client-show-prestation col-md-6">
          <div class="name-email-client-show-prestation">
            <h2 class="client-name-title-show-prestation pl-3 pt-4 mt-2 ml-4 mb-2"> <%= @prestation.client.first_name %> <%= @prestation.client.last_name %> </h2>
            <p class="email-client-show-prestation pl-3 ml-4 pb-3"> <%= @prestation.client.email %></p>
          </div>
          <div class="contact-info-client-show-prestation pl-5">
            <p class="pb-2 pt-4 phone-number-client-show-prestation p-gray"> <i class="fas fa-phone"></i> <%= @prestation.client.phone_number %> </p>
            <p class="py-2 p-gray"> <i class="fas fa-home"></i> <%= @prestation.client.address  %> </p>
            <% if @prestation.client.partner_name.nil? == false %>
              <p class="py-2 partner-name p-gray"> <i class="fas fa-plus-circle"></i> <%= @prestation.client.partner_name %> </p>
            <% end %>
            <%if @prestation.client.tutoiement == true %>
              <p class="py-2 pb-4 tutoiement-square p-gray"><i class="fas fa-comment"></i> On se tutoie </i></p>
            <% else %>
              <p class="py-2 pb-4 tutoiement-square p-gray"><i class="fas fa-comment"></i> On se vouvoie </i></p>
            <% end %>
          </div>
        </div>
        <div class="photo-client-show-prestation d-flex col-md-6">
          <%= cl_image_tag @prestation.client.photo.key, crop: :fill, width: 270, height: 270, class: "photo-client" %>
        </div>
      </div>

      <div class="notes-show-prestation bg-white flex-grow-1">
        <h2 class="notes-title-show-prestation pl-3 pt-4 mt-4 ml-4 mb-2 pb-2"> Notes </h2>
        <div class="notes-show-prestation d-flex pl-5">
          <p class="pb-5"><%= @prestation.notes %></p>
        </div>
      </div>
    </div>
  </div>
</div>