config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :prestations, except: :destroy do
    member do
      patch :finish
    end
  end

  # POST "prestations/51/finish"
  # post "prestations/finish", to: 'prestations#finish', as: :finish_prestation

  resources :tasks, only: [:index, :show, :edit, :update] do
    collection do
      get :calendar
    end

    member do
      get :index
      patch :mark_as_urgent
      patch :mark_as_done
    end
  end

  resources :clients, only: [:index, :show]
end

app/models/task.rb
class Task < ApplicationRecord
  KINDS = ['rendez-vous', 'admin', 'créa', 'évènement']

  belongs_to :prestation

  validates :name, presence: true
  validates :kind, presence: true, inclusion: { in: KINDS }
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update mark_as_urgent mark_as_done]

  def index
    tasks = Task.joins(prestation: :client).where(clients: { user_id: current_user.id })
    today = Date.today

    # Afficher toutes les Tasks par order chronologique des 7 prochains jours, dont kind = 'admin' ou 'créa'
    @todo = tasks.
      where(kind: ['admin', 'créa']).
      where('tasks.start_date BETWEEN ? AND ?', today, (today + 7.days)).
      order("tasks.start_date")

    @todo_by_day = @todo.group_by(&:start_date)

    # Afficher les 6 prochains Tasks dont kind = 'évènement'
    @evenement = tasks.
      where(kind: 'évènement').
      where('tasks.start_date >= ?', today).
      order("tasks.start_date").
      first(5)

    # Afficher les 3 prochains Tasks dont kind = 'rendez-vous'
    @rdv = tasks.
      where(kind: 'rendez-vous').
      where('tasks.start_date >= ?', today).
      order("tasks.start_date").
      first(3)
  end

  def show; end

  def edit; end

  def update
    @task.update(task_params)

    if @task.save
      respond_to do |format|
        format.html { redirect_to task_path(@task) }
        format.js  # <-- will render `app/views/tasks/update.js.erb`
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.js  # <-- idem
      end
    end
  end

  def mark_as_urgent
    if @task.urgent
      @task.update(urgent: false)
    else
      @task.update(urgent: true)
    end

    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.js  # <-- will render `app/views/tasks/mark_as_done.js.erb`
    end
  end

  def mark_as_done
    if @task.done
      @task.update(done: false)
    else
      @task.update(done: true)
    end

    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.js  # <-- will render `app/views/tasks/mark_as_done.js.erb`
    end
  end

  def calendar
    # Build all displayed dates range
    @today = Date.today

    month_start_date          = @today.beginning_of_month
    month_start_date_week_day = month_start_date.wday
    month_starts_on_sunday    = month_start_date_week_day == 0
    start_offset = month_starts_on_sunday ? 6 : month_start_date_week_day - 1
    calendar_start_day = month_start_date - start_offset.day
    month_end_date          = @today.end_of_month
    month_end_date_week_day = month_end_date.wday
    month_ends_on_sunday    = month_end_date_week_day == 0
    end_offset = month_ends_on_sunday ? 0 : 7 - month_end_date_week_day
    calendar_end_day = month_end_date + end_offset.day
    all_days_to_display_in_calendar_view = (calendar_start_day..calendar_end_day)

    @all_days = all_days_to_display_in_calendar_view.to_a

    @days_current_month = (month_start_date..month_end_date).to_a

    #@days_by_week = @all_days.first(7)
    # Load all tasks for current month
    @day_tasks = current_user.tasks.
      where('tasks.start_date BETWEEN ? AND ?', month_start_date, month_end_date).
      order("tasks.start_date ASC")

    @tasks_by_day = @day_tasks.group_by(&:start_date)
  end

  private

  def set_task
    tasks = Task.joins(prestation: :client).where(clients: { user_id: current_user.id })
    @task = tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :start_date, :end_date, :urgent, :done)
  end
end

app/views/tasks/_cardtask.html.erb
<%= link_to mark_as_urgent_task_path(task), class: "link-mark-as-urgent", method: :patch, remote: true do %>
  <% if task.kind == "admin" %>
    <% if task.urgent == true %>
      <div id="tag-urgent-<%= task.id %>" class="tag-urgent urgent col-1 pl-0 pr-1"><i class="fas fa-thumbtack"></i></div>
    <% else %>
      <div id="tag-urgent-<%= task.id %>" class="tag-urgent p-gray col-1 pl-0 pr-1"><i class="fas fa-thumbtack"></i></div>
    <% end %>
  <% else %>
    <% if task.urgent == true %>
      <div id="tag-urgent-<%= task.id %>" class="tag-urgent urgent col-1 pl-0 pr-1"><i class="fas fa-palette"></i></i></div>
    <% else %>
      <div id="tag-urgent-<%= task.id %>" class="tag-urgent p-gray col-1 pl-0 pr-1"><i class="fas fa-palette"></i></i></div>
    <% end %>
  <% end %>
<% end %>

<%= link_to mark_as_done_task_path(task), class: "link-mark-as-done", method: :patch, remote: true do %>
  <% if task.done %>
    <div id="tag-done-<%= task.id %>" class="tag-done green col-1 px-0"><i class="fas fa-check"></i></div>
  <% else %>
    <div id="tag-done-<%= task.id %>" class="tag-done p-gray col-1 px-0"><i class="fas fa-check"></i></div>
  <% end %>
<% end %>
<!-- Rajouter le lien vers la show de la Tâche -->
<div class="col-6">
  <p class="task-name"><%= task.name %></p>
</div>

<%= link_to prestation_path(task.prestation), class: "card-task-link col-4 px-0" do %>
  <p class="task-prestation-client text-right p-gray"><%= task.prestation.category.upcase %> - <%=  task.prestation.client.last_name %></p>
<% end %>

app/views/tasks/_editform.html.erb
<!-- TASK EDIT -->
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col px-0">
      <div class="form-post mb-5">
        <!-- <h1 class="mt-3 mb-5">Modifier la tâche<span class="green-point">.</span></h1> -->
        <%= simple_form_for(task, remote: true) do |f| %>

          <!-- Error message -->
          <% if task.errors.any? %>
            <div class="errors-container">
              <ul>
                <% task.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <!-- Form -->

            <%= f.input :description,
                        as: :text,
                        label: 'Description' %>


            <div class="row">
              <div class="start-date col">
                <%= f.input :start_date,
                            as: :string,
                            required: false,
                            input_html: {class: "datepicker"},
                            label: 'Dates' %>
              </div>
              <div class="end-date col">
                <%= f.input :end_date,
                            as: :string,
                            required: false,
                            input_html: {id: "end_date", class: "end_date"},
                            label: 'Date de fin' %>
              </div>
            </div>
            <div class='dates-div d-none'>
              <label>Dates</label>
                <input type="text" id="range-dates">
            </div>

            <%= f.input :urgent,
                        as: :radio_buttons,
                        wrapper: :vertical_collection_inline,
                        collection: ['Oui','Non'],
                        label: 'Urgent' %>

            <%= f.input :done,
                        as: :radio_buttons,
                        wrapper: :vertical_collection_inline,
                        collection: ['Oui','Non'],
                        label: 'Terminée' %>

            <div class="d-flex flex-row-reverse mt-4">
              <%= f.submit "Valider", class: 'validate pho-btn' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- END OF TASK EDIT -->

app/views/tasks/_infotask.html.erb
<!-- TASK SHOW -->
<div class="container-fluid">


  <!-- Infos Prestation & Client -->
  <div class="row my-4 justify-content-between align-items-center">
    <div class="col-6 px-0">
      <p class="px-0 m-gray"><%= task.prestation.category.upcase %> - <%= task.prestation.client.last_name %></p>
    </div>
    <div class="col-6 px-0">
      <% if task.prestation.start_date != task.prestation.end_date %>
        <p class="text-right m-gray"><%= l(task.prestation.start_date, format: '%d') %> - <%= l(task.prestation.end_date, format: '%d %B %Y') %></p>
      <% else %>
        <p class="text-right m-gray"><%= l(task.prestation.start_date, format: '%d %B %Y') %></p>
      <% end %>
    </div>
  </div>

  <!-- Task name -->
  <div class="row justify-content-between align-items-center">
    <div class="task-name">
      <h2><%= task.name %></h2>
    </div>
    <div class="col">
      <div class="e-mail-task">
      <%= render "tasks/emails/#{mailto_partial_for_task(task)}", task: task, :@prestation => task.prestation, class: "e-mail-task" %>
      </div>
    </div>
  </div>

  <!-- Task dates -->
  <div class="row mt-1 justify-content-between">
    <div class="col px-0">
      <!-- <p class="medium-gray"><i class="far fa-calendar mr-2"></i> <%= l(task.start_date, format: '%d %B') %></p> -->
      <% if task.urgent %>
        <% if task.start_date == Date.today %>
          <p class="medium-gray"><i class="far fa-calendar mr-2"></i> Aujourd'hui - <span class="bright-red">urgent</span></p>
        <% elsif task.start_date == Date.tomorrow %>
          <p class="medium-gray"><i class="far fa-calendar mr-2"></i> Demain - <span class="bright-red">urgent</span></p>
        <% else %>
          <% if task.start_date.cweek == Date.today.cweek %>
            <p class="medium-gray"><i class="far fa-calendar mr-2"></i> <%= l(task.start_date, format: '%A') %> - <span class="bright-red">urgent</span></p>
          <% else %>
            <p class="medium-gray"><i class="far fa-calendar mr-2"></i> <%= l(task.start_date, format: '%d %B') %> - <span class="bright-red">urgent</span></p>
          <% end %>
        <% end %>
      <% else %>
        <% if task.start_date == Date.today %>
          <p class="medium-gray"><i class="far fa-calendar mr-2"></i> Aujourd'hui</p>
        <% elsif task.start_date == Date.tomorrow %>
          <p class="medium-gray"><i class="far fa-calendar mr-2"></i> Demain</p>
        <% else %>
          <% if task.start_date.cweek == Date.today.cweek %>
            <p class="medium-gray"><i class="far fa-calendar mr-2"></i> <%= l(task.start_date, format: '%A') %></p>
          <% else %>
            <p class="medium-gray"><i class="far fa-calendar mr-2"></i> <%= l(task.start_date, format: '%d %B') %></p>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <!-- Task description -->
  <div class="row my-3 task-description">
    <p class="text-justify medium-gray"><%= task.description %></p>
  </div>
  <!-- Modify button -->
  <div class="row justify-content-end">
    <button class="modify pho-btn">Modifier</button>
  </div>
</div>
<!-- END OF TASK SHOW -->

app/views/tasks/_show.html.erb
<div class="container">
  <div class="task-show row">
    <div class="col px-5">
      <!-- Close button -->
      <div class="row">
        <div class="col px-0">
          <button type="button" class="close mt-5" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      <!-- TASK SHOW -->
      <div id="info-task-<%= task.id %>">
        <%= render 'infotask', task: task %>
      </div>
    </div>
  </div>
  <div class="task-form row d-none">
    <div class="col px-5">
      <!-- TASK EDIT FORM -->
      <%= render 'editform', task: task %>
    </div>
  </div>
</div>

app/views/tasks/calendar.html.erb
<div class="d-flex w-100 justify-content-center" id="all-calendar">
  <div class="calendar-col bg-white">
    <div class="principale-calendar-task">
      <h3 class="calendar-title"> <%= l(@today, format: '%B %Y') %></h3>
      <div class="calendar">

        <% @all_days.in_groups_of(7) do |week| %>
          <div class="calendar-week-view d-flex justify-content-center">
            <% week.each do |day| %>
              <div class="calendar-day-view d-flex" date="<%= day %>">
                <% if @days_current_month.find {|d| day == d } %>
                  <% if @tasks_by_day.keys.find {|td| day == td } %>
                    <% if day >= @today && @tasks_by_day[day].any? { |task| task.kind == "évènement"} %>
                      <p class="today"><%= l(day, format: '%d') %></p>
                    <% elsif day < @today %>
                      <p class="day-task-past"><%= l(day, format: '%d') %></p>
                    <% else %>
                      <p class="day-task"><%= l(day, format: '%d') %></p>
                    <% end %>
                  <% else %>
                  <% if day < @today %>
                    <p class="day-past"><%= l(day, format: '%d') %></p>
                  <% elsif day == @today %>
                  <p class="today"><%= l(day, format: '%d') %></p>
                  <% else %>
                    <p class="day"><%= l(day, format: '%d') %></p>
                  <% end %>

                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="tasks-col">
    <div class="display-task">
      <h1 class="task-title-calendar pb-2 mt-4">Tâches<span class="green-point">.</span></h1>

      <div id="today-message">
        <% unless @tasks_by_day.key?(@today)%>
          <div class="details-day-calendar" date="<%= @today %>">
            <h4 class="text-center pb-4"><%= l(@today, format: '%d %B') %></h4>
            <p class="text-center no-task mt-3">Vous n'avez pas de tâche pour aujourd'hui.</p>
          </div>
        <% end %>
      </div>
      <!-- TASK -->
      <% @tasks_by_day.each do |day, tasks| %>
        <div class="details-day-calendar <%= "d-none" unless day == @today %>" date="<%= day %>">
          <h4 class="pickup-day pb-4"><%= l(day, format: '%d %B') %></h4>
          <!-- Sub Task -->
          <% tasks.each do |task| %>
            <div class="task-per-day mx-4">
              <div class="d-flex">
                <%= link_to mark_as_urgent_task_path(task), class: "link-mark-as-urgent", method: :patch, remote: true do %>
                  <% if task.kind == 'admin' %>
                    <% if task.urgent == true %>
                      <div id="tag-urgent-<%= task.id %>" class="urgent pl-4"><i class="fas fa-thumbtack picto-task-calendar"></i></div>
                    <% else %>
                      <div id="tag-urgent-<%= task.id %>" class="p-gray pl-4"><i class="fas fa-thumbtack picto-task-calendar"></i></div>
                    <% end %>
                    <% elsif task.kind == 'évènement' %>
                      <div id="tag-urgent-<%= task.id %>" class="pl-4"><i class="p-gray picto-task-calendar fas fa-camera"></i></div>
                  <% else %>
                    <% if task.urgent == true %>
                      <div id="tag-urgent-<%= task.id %>" class="urgent pl-4"><i class="fas fa-palette picto-task-calendar"></i></i></div>
                    <% else %>
                      <div id="tag-urgent-<%= task.id %>" class="p-gray pl-4"><i class="fas fa-palette picto-task-calendar"></i></i></div>
                    <% end %>
                  <% end %>
                <% end %>
                <%= link_to mark_as_done_task_path(task), class: "link-mark-as-done", method: :patch, remote: true do %>
                  <% if task.done %>
                    <div id="tag-done-<%= task.id %>" class="tag-done green pl-2"><i class="fas picto-task-calendar fa-check"></i></div>
                  <% else %>
                    <div id="tag-done-<%= task.id %>" class="tag-done p-gray pl-2"><i class="fas picto-task-calendar fa-check"></i></div>
                  <% end %>
                <% end %>
                <% if task.kind == 'évènement'  %>
                  <p class="col-6 px-4 font-weight-bold title-task green"><%= task.name %></p>
                  <%= link_to prestation_path(task.prestation), class: "link-text-index" do %>
                    <p class="p-gray px-0 task-prestation-title-calendar green"><%= task.prestation.category.upcase %> - <%=  task.prestation.client.last_name %></p>
                  <% end %>
                <% else %>
                  <p class="col-6 px-4 font-weight-bold title-task"><%= task.name %></p>
                  <%= link_to prestation_path(task.prestation), class: "link-text-index" do %>
                    <p class="p-gray px-0 task-prestation-title-calendar"><%= task.prestation.category.upcase %> - <%=  task.prestation.client.last_name %></p>
                  <% end %>
                <% end %>
              </div>
              <% if task.description %>
                <p class="description-task-calendar text-center pb-3 d-none"><%= task.description %></p>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container task-form">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="form-post mb-5">
        <h1 class="mt-3 mb-5">Modifier la tâche<span class="green-point">.</span></h1>
        <%= simple_form_for @task do |f| %>

          <!-- Error message -->
          <% if @task.errors.any? %>
            <div class="errors-container">
              <ul>
                <% @task.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <!-- Form -->

            <%= f.input :name,
                        as: :string,
                        label: 'Titre' %>

            <%= f.input :kind,
                        as: :select,
                        collection: Task::KINDS,
                        input_html: {class: "select2"},
                        label: 'Type' %>

            <%= f.input :description,
                        as: :text,
                        label: 'Description' %>


            <div class="row">
              <div class="start-date col">
                <%= f.input :start_date,
                            as: :string,
                            required: false,
                            input_html: {class: "datepicker"},
                            label: 'Date de début' %>
              </div>
              <div class="end-date col">
                <%= f.input :end_date,
                            as: :string,
                            required: false,
                            input_html: {id: "end_date", class: "end_date"},
                            label: 'Date de fin' %>
              </div>
            </div>
            <div class='dates-div d-none'>
              <label>Dates</label>
                <input type="text" id="range-dates">
            </div>

            <%= f.input :urgent,
                        as: :radio_buttons,
                        wrapper: :vertical_collection_inline,
                        label: 'Urgent' %>

            <%= f.input :done,
                        as: :radio_buttons,
                        wrapper: :vertical_collection_inline,
                        label: 'Terminée' %>

            <div class="d-flex flex-row-reverse mt-4">
              <%= f.submit "Modifier", class: 'pho-btn' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container-fluid" id="dashboard">
  <div class="row h-100">
    <div class="col-7 px-0">
      <div class="dashboard-todo pt-5 px-5 p-4 h-100">
        <div class="d-flex mb-5 align-items-end justify-content-between">
          <h1 class="">Tâches<span class="green-point">.</span></h1>
          <h4><%= l(Date.today, format: '%A %d %B') %> <i class="far fa-calendar-alt"></i></h4>
        </div>
          <ul>
            <li>
              <% @todo_by_day.each do |day, tasks| %>
                <div class="day-tasks mb-5">
                  <% if day == Date.today %>
                    <h3 class="mb-3">Aujourd'hui</h3>
                  <% elsif day == Date.tomorrow %>
                    <h3 class="mb-3">Demain</h3>
                  <% else %>
                    <% if day.cweek == Date.today.cweek %>
                      <h3 class="mb-3"><%= l(day, format: '%A') %></h3>
                    <% else %>
                      <h3 class="mb-3"><%= l(day, format: '%A %d %B') %></h3>
                    <% end %>
                  <% end %>
                  <ul class="container-fluid">
                    <% tasks.each do |task| %>
                    <li class="card-task row align-items-center justify-content-between py-2 px-2">
                      <div id="card-task-<%= task.id %>" class="col d-flex justify-content-between">
                        <%= render 'cardtask', task: task %>
                      </div>
                      <!-- Slide-in : Task #Show -->
                      <div class="cd-panel js-cd-panel-main">
                        <div class="cd-panel__container">
                          <%= render 'show', task: task %>
                        </div>
                      </div>
                    </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </li>
          </ul>
      </div>
    </div>
    <div class="col-5 px-0">
      <div class="dashboard-interactions">
        <div class="dashboard-evenements pt-5 px-5 p-4 h-50">
          <h1 class="mb-5">Évènements<span class="green-point">.</span></h1>
          <ul class="container-fluid">
            <% @evenement.each do |task| %>
              <% if task.start_date == Date.today %>
                <%= link_to prestation_path(task.prestation), class: "card-task-link" do %>
                  <li class="card-date-task row align-items-center my-1">
                    <% if task.start_date != task.end_date %>
                      <p class="col-3 green-point font-weight-bold"><%= l(task.start_date, format: '%d') %> - <%= l(task.end_date, format: '%d %b') %></p>
                    <% else %>
                      <% if task.start_date == Date.today %>
                        <p class="col-3 green-point font-weight-bold">Aujourd'hui</p>
                      <% elsif task.start_date == Date.tomorrow %>
                        <p class="col-3 green-point font-weight-bold">Demain</p>
                      <% else %>
                        <% if task.start_date.cweek == Date.today.cweek %>
                          <p class="col-3 green-point font-weight-bold"><%= l(task.start_date, format: '%A') %></p>
                        <% else %>
                          <p class="col-3 green-point font-weight-bold"><%= l(task.start_date, format: '%d %B') %></p>
                        <% end %>
                      <% end %>
                    <% end %>
                    <p class="col-9 pl-3 font-weight-bold"><%= task.prestation.category.upcase %> - <%=  task.prestation.client.last_name %></p>
                  </li>
                <% end %>
              <% else %>
                <%= link_to prestation_path(task.prestation), class: "card-task-link" do %>
                  <li class="card-date-task row align-items-center my-1">
                    <% if task.start_date != task.end_date %>
                      <p class="col-3 green-point"><%= l(task.start_date, format: '%d') %> - <%= l(task.end_date, format: '%d %b') %></p>
                    <% else %>
                      <% if task.start_date == Date.tomorrow %>
                        <p class="col-3 green-point">Demain</p>
                      <% else %>
                        <% if task.start_date.cweek == Date.today.cweek %>
                          <p class="col-3 green-point"><%= l(task.start_date, format: '%A') %></p>
                        <% else %>
                          <p class="col-3 green-point"><%= l(task.start_date, format: '%d %B') %></p>
                        <% end %>
                      <% end %>
                    <% end %>
                    <p class="col-9 pl-3"><%= task.prestation.category.upcase %> - <%=  task.prestation.client.last_name %></p>
                  </li>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class="dashboard-rdv pt-5 px-5 p-4 h-50">
          <h1 class="mb-4">RDV<span class="green-point">.</span></h1>
          <ul class="container-fluid">
            <% @rdv.each do |task| %>
              <% if task.start_date == Date.today %>
                <%= link_to prestation_path(task.prestation), class: "card-task-link" do %>
                  <li class="card-date-task row align-items-top mb-2">
                    <% if task.start_date != task.end_date %>
                      <p class="col-3 green-point font-weight-bold"><%= l(task.start_date, format: '%d') %> - <%= l(task.end_date, format: '%d %b') %></p>
                    <% else %>
                      <p class="col-3 green-point font-weight-bold">Aujourd'hui</p>
                    <% end %>
                    <div class="col-9 pl-3">
                      <p class="font-weight-bold"><%= task.name %></p>
                      <p class="p-gray font-weight-bold"><%= task.prestation.category.upcase %> - <%=  task.prestation.client.last_name %></p>
                    </div>
                  </li>
                <% end %>
              <% else %>
                <%= link_to prestation_path(task.prestation), class: "card-task-link" do %>
                  <li class="card-date-task row align-items-top mb-2">
                    <% if task.start_date != task.end_date %>
                      <p class="col-3 green-point"><%= l(task.start_date, format: '%d') %> - <%= l(task.end_date, format: '%d %b') %></p>
                    <% else %>
                      <% if task.start_date == Date.tomorrow %>
                        <p class="col-3 green-point">Demain</p>
                      <% else %>
                        <% if task.start_date.cweek == Date.today.cweek %>
                          <p class="col-3 green-point"><%= l(task.start_date, format: '%A') %></p>
                        <% else %>
                          <p class="col-3 green-point"><%= l(task.start_date, format: '%d %B') %></p>
                        <% end %>
                      <% end %>
                    <% end %>
                    <div class="col-9 pl-3">
                      <p><%= task.name %></p>
                      <p class="p-gray"><%= task.prestation.category.upcase %> - <%=  task.prestation.client.last_name %></p>
                    </div>
                  </li>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/mark_as_done.js.erb
function changeDoneTag () {
  const tagDone = document.querySelector("#tag-done-<%= @task.id %>");

  if (tagDone.classList.contains("green")) {
      tagDone.classList.remove("green");
      tagDone.classList.add("p-gray");
    } else {
      tagDone.classList.remove("p-gray");
      tagDone.classList.add("green");
  }
}

changeDoneTag();

app/views/tasks/show.html.erb
<div class="container-fluid px-5 task-show">

  <!-- Close button -->
  <div class="row">
    <div class="col px-0">
      <button type="button" class="close pt-5" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>

  <!-- Infos Prestation & Client -->
  <div class="row my-4 justify-content-between align-items-center">
    <div class="col-6 px-0">
      <p class="px-0 m-gray"><%= @task.prestation.category.upcase %> - <%= @task.prestation.client.last_name %></p>
    </div>
    <div class="col-6 px-0">
      <% if @task.prestation.start_date != @task.prestation.end_date %>
        <p class="text-right m-gray"><%= l(@task.prestation.start_date, format: '%d') %> - <%= l(@task.prestation.end_date, format: '%d %B %Y') %></p>
      <% else %>
        <p class="text-right m-gray"><%= l(@task.prestation.start_date, format: '%d %B %Y') %></p>
      <% end %>
    </div>
  </div>

  <!-- Task name -->
  <div class="row justify-content-between align-items-center">
    <div class="task-name">
      <h2><%= @task.name %></h2>
    </div>
  </div>

  <!-- Task dates -->
  <div class="row mt-1 justify-content-between">
    <div class="col px-0">
      <p class="medium-gray"><i class="far fa-calendar mr-2"></i> <%= l(@task.start_date, format: '%d %B') %></p>
    </div>
  </div>




  <!-- Task description -->
  <div class="row my-3 task-description">
    <p class="text-justify medium-gray"><%= @task.description %></p>
  </div>

    <div class="col px-0 d-flex justify-content-end align-items-center">
      <!-- Tag urgent -->
   <!--    <div class="urgent-tag mr-3">
        <p>urgent</p>
      </div> -->
      <!-- Tag TODO -->
     <!--  <div class="todo-tag mr-3">
        <p>à faire</p>
      </div> -->
    </div>

  <!-- Modify button -->
  <div class="row justify-content-end">
    <%= link_to 'Modifier', prestation_path(@task.prestation), class: "pho-btn" %>
  </div>
</div>