config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :prestations, except: :destroy do
    member do
      patch :finish
    end
  end

  # POST "prestations/51/finish"
  # post "prestations/finish", to: 'prestations#finish', as: :finish_prestation

  resources :tasks, only: [:index, :show, :edit, :update] do
    collection do
      get :calendar
    end

    member do
      get :index
      patch :mark_as_urgent
      patch :mark_as_done
    end
  end

  resources :clients, only: [:index, :show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar-container">

  <div class="sidebar-menu">

    <div>
      <ul>
        <div class="menu-item-box">
          <a href='/tasks' id="logo-link"><li id="logo">P<span id="logo-point">.</span></li></a>
        </div>
       <!--  <div class="menu-item-box">
          <li><i class="fas fa-search"></i></li>
        </div> -->
        <div class="menu-item-box">
          <li><%= link_to(new_prestation_path, class: 'i-links') do %>
            <i class="fas fa-plus-circle"></i>
            <% end %>
          </li>
        </div>
        <div class="menu-item-box">
          <li><%= link_to(calendar_tasks_path, class: 'i-links') do %>
            <i class="fas fa-calendar-alt"></i>
            <% end %>
          </li>
        </div>
        <div class="menu-item-box">
          <li><%= link_to(clients_path, class: 'i-links') do %>
            <i class="fas fa-users"></i></li>
            <% end %>
        </div>
        <div class="menu-item-box">
          <li><%= link_to(prestations_path, class: 'i-links') do %>
                <i class="fas fa-camera"></i>
              <% end %>
          </li>
        </div>
      </ul>
    </div>

    <div>
      <div class="user-picture">
          <% if current_user.photo.attached? %>
            <%= link_to (cl_image_tag current_user.photo.key, class: "avatar"), destroy_user_session_path, method: :delete %>
          <% else %>
          <%= image_tag "icon-avatar.jpg", class: "avatar" %>
          <% end %>
      </div>

      <div id="toggle-button">
        <i class="fas fa-chevron-right"></i>
      </div>
    </div>

  </div>

  <div class="sidebar-toggle hide-sidebar">
    <div class='d-flex flex-column justify-content-between'>
      <div>
        <ul>
          <div class="menu-item-box">
            <li><p>Chercher</p></li>
          </div>
          <div class="menu-item-box">
            <li><p><%= link_to 'Ajouter', new_prestation_path, class: 'text-links' %></p></li>
          </div>
          <div class="menu-item-box">
            <li><p><%= link_to 'Tâches', calendar_tasks_path, class: 'text-links' %></p></li>
          </div>
          <div class="menu-item-box">
            <li><p>Clients</p></li>
          </div>
          <div class="menu-item-box">
            <li><p><%= link_to 'Prestations', prestations_path, class: 'text-links' %></p></li>
          </div>
        </ul>
      </div>
      <div id="deconnexion">
         <p><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: 'text-links' %></P>
      </div>
    </div>
  </div>
</div>